#!/usr/bin/env node
let program = require('commander');
let rm = require('rimraf')

program
    .version('1.0.0','-v, --version')
    .option('-w, --watch', '监视目录改动')

program
    .command('clean')
    .description('清空build目录')
    .action(()=>{
      rm('./build/',  ()=>{ console.log('已清空')})
    })

program
    .command('build')
    .description('编译项目')
    .action(()=>{
      require('./lib/build')
    })

program
    .command('new <project>')
    .description('新建项目')
    .action((project)=>{
      require('./lib/create')(project)
    })

program
    .command('upgrade')
    .description('更新')
    .action(()=>{
      require('./lib/upgrade')
    })

program.parse(process.argv)